{% set xorg_name = "libXi" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/lib/{{ xorg_name }}-{{ version }}.tar.xz
  sha256: d0e0555e53d6e2114eabfa44226ba162d2708501a25e18d99cfb35c094c6c104

build:
  number: 0
  # xorg-libxdmcp, libxcb, libx11, libice aren't available on Windows because their dependencies clash with m2/msys2 and mingw64/ucrt64 toolchains.
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config
    - gnuconfig
    - make
    - autoconf
    - automake
    - libtool
  host:
    - pthread-stubs
    - xorg-xorgproto
    - xorg-libx11 >=1.6,<2
    # Additional constraintless xorg-libx11 dep below is for conda-build to add potential pinning to.
    - xorg-libx11
    - xorg-libxext 1.3.*
    - xorg-libxfixes 6.*
    - xorg-util-macros
  run:
    - {{ pin_compatible('xorg-libx11') }}

test:
  commands:
    - test -f $PREFIX/lib/{{ xorg_name }}.dylib  # [osx]
    - test -f $PREFIX/lib/{{ xorg_name }}.so     # [linux]

about:
  home: https://www.x.org/
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libxi
  doc_url: https://gitlab.freedesktop.org/xorg/lib/libxi
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The X.org input library.
  description: The X.org input library.

extra:
  recipe-maintainers:
    - pkgw
