{% set name = "xorg-libXi" %}
{% set version = "1.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/lib/{{ name.split('-')[1] }}-{{ version }}.tar.xz
  sha256: 7ad60056f01af4f786cfe93b3a7707447711626fc8da2637bec71a90409babe5

build:
  number: 0
  # xorg-libxdmcp, libxcb, libx11, libice aren't available on Windows because their dependencies clash with m2/msys2 and mingw64/ucrt64 toolchains.
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config
    - gnuconfig
    - make
    - autoconf
    - automake
    - libtool
  host:
    - pthread-stubs ==0.3
    - xorg-xorgproto {{ xorg_xorgproto }}
    - xorg-libx11 {{ xorg_libx11 }}
    - xorg-libxext {{ xorg_libxext }}
    - xorg-libxfixes {{ xorg_libxfixes }}
    - xorg-util-macros ==1.20.2
  run:
    - {{ pin_compatible('xorg-libx11') }}

test:
  commands:
    - test -f $PREFIX/lib/libXi.dylib  # [osx]
    - test -f $PREFIX/lib/libXi.so     # [linux]

about:
  home: https://www.x.org/
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libxi
  doc_url: https://gitlab.freedesktop.org/xorg/lib/libxi
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The X.org input library.
  description: The X.org input library.

extra:
  recipe-maintainers:
    - pkgw
