appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: pXnsQwdHg4zJhupAyxWGDDyg0BboliIpmV408WfeJpuByy6Rq4TdI/PV+hNwOGv+4tc1xDET6SEwQf8qcA8Zm+1uAlTMxChR7H1KaDdL/OOKPYXVjFowzzhlEeO3rsm5c9vYIqCln7zNXST1eUrt5gLszKOuWJp4wCA+qZQ9XPlPxEOnA7BLLtzv/AWhl3/cuIRl8aa91JVp1gp5+SBnG/iyYstokS59S9vJusoxRNT+II+YIT4tSWtIZBCLpaj1wadxJ5YK62ok9Emdh4c58n7KCzXG5LVTbcEC9jF9SYKg5czyEim5PjvFLzfZG1nQ6CHeUtbD3VxzRjpselrOMXjMor2dErISfHULitv5H3eKF6S6NvFEUhASK8KF2RUu3RMzksDXe52JrVpu4YB3m2W5Q9s/ZqkRgNEEHRtik+/ve7J/+Ukzeg9AfJpzvvJ56egLNyuGFNiMIT7wEN1iM0LPdJDvU6dBv27r2kNxZoJYljb5C75nTbeXPldLpBv2FaC7umHpWDIxcuweDWoswZtUMCCSRM3FMf8JQuW4Ih1XSoQzoHJ8FSml8JN4Vm4CjEGnB/lJrIGONmtj7ytlFo1uBwDiL6ZSM9C4iLTN5tV6Sj50j4h6W3ckEObasoLzDWkKgNFi+GaLO78bUGpBVX3/qcqVUIEkcJIy76KF/wQ=}
conda_forge_output_validation: true
