travis:
  secure:
    BINSTAR_TOKEN: bZhyJkbhHN8sUZPSDCjhw6Hj4+Oh2tY3/yHFhtJuxE9LhZi24NaEcc3y78DqIqNEvmCsveN+2ITPEx7UdWL+LO5iA8OHG4OolUx3PZheGq85ONOVTn7Xjuxaj1cYMV2iCTzPgpt0f/kaKdvs6Zuu7BZWn19cEKhirUk44K0M1aiedcc1F5+UJj7AsxIw8Kay9c3EYNhT8e0VDlUp3uMfTXYj4TfaZYIFT0/ve7yki369tuf1YSKtB8UU64F1REv0h3SDrGuLXh09119PH9uVkgh+iXDNDYdflJld6YmL6VRkHSu1e8X77m4Bx2qpTSiKG7hOkwIpUTAXxY9254eRgk0zkFeZfF6xTT/VavfFc0NywOel07ffIg41fZCJSYG154Teg8Rdf2nXSpUWqflu8QGSDwUA/PBSRoKrgUpLOUGL3ith2HXtUEQylJeHTtF7QD16iiI11QEuTrfWN4C99w1U9gcKvFF3iG/B9CPM04Um7Ttnb+EwNofwm4q4PuWYewjeUiKoVHJnTWMIrkvNPF7wnA/JCaBi7Z6R2SlTpPDAg+XFuct1kDNs4ODFCmbRs4E6fm+VErAxKBl/tdXCFJ11WjMCtMb/MjhNenoBRSctifetbbq9GMS+IgyVh3uYV5oIEpy6CauJvqU5glANW086IAPIddMrx+QCYIE6wzo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
