travis:
  secure:
    BINSTAR_TOKEN: LrOOc4PyisW75zUXbQoCwcivn/MoMa4I7kO8hUI+PDFceJwtJx7OzE5Npq29SxrTYhB2MuYhcPfIORiq7u1+pjV6v593Lu5HAARx5fRSh4tglHXqVEk06UOsw+hWM8btl/vfzw/F7FWUec4olKr/lsjss7I+i/YO8e3R1bSzLlL8EIuqVNy8bmibNfDwUvUw/Qi9N0YTCB6dggqY+sNAck7PmvOgvDl+R79GPWevj+qdjCyi+U4r4pncfc0ffi1W6yIU2eVJrRgi+frl9LhW5MoHr5SQXVL+fyWYWIumOxOhqnbEaOtbEIh5/O6zm9pYavxOlZ+rWI6Qu2GvG2/MTegbNOWVfuPb5M6/EIsEopwPZi3wUT4lhRAss/irUC3YFk62IQc0zkeC5Fq8k4B4R8XeaLkqQYMOkxk7Pm9WvdS6XPvBPoPwtjefrrMJowKrBzvfbW006FIOwkXDPPiAI6NcfoxMoqb0YdAxLV1teu1Io+rdrO5Q6QQswSO99YmCD/gXgXF9pHeXD9DCD8m1izYVRLivLQW1Yn9Z8M6UWFSHsQaCFm/nyNWjeRbTlwjS5QgJfq9xsvs5vYef8dWa48MW/WfLAuN9TcrM93uSz9fTfggkxNUo1xQcHcaqyERc9P0uVEDPaGnQ4bnZJOoJVv3bsbTF7HEtD8x9eRjcuBQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
